export const POST_API_STARTED = 'POST_API_STARTED';
export const POST_DATA_SUCCESS = 'POST_DATA_SUCCESS';
export const POST_DATA_FAILURE = 'POST_DATA_FAILURE';

export const CLICKED_POST_API = "CLICKED_POST_API";